/* Sapientia — Administração Pública v2
   Substitui 30 variantes quase idênticas por questões conceitualmente distintas.
   Deve ser carregado depois da declaração de DATA e antes do módulo de auditoria.
*/
(() => {
  if (typeof DATA === "undefined" || !Array.isArray(DATA)) return;

  const replacements = [
    {id:"1-1-2",q:"Um servidor recebe ordem verbal para praticar ato que contraria norma vigente. À luz do princípio da legalidade, a conduta correta é:",options:["cumprir a ordem porque veio de superior hierárquico","recusar a prática ilegal e observar o ordenamento aplicável","cumprir e registrar posteriormente","agir conforme o costume do setor"],answer:"recusar a prática ilegal e observar o ordenamento aplicável",explanation:"A atuação administrativa está vinculada ao ordenamento jurídico; ordem hierárquica não legitima conduta ilegal.",basis:"CF/88, art. 37, caput; princípio da legalidade."},
    {id:"1-1-3",q:"Em comparação com o particular, a legalidade administrativa significa que o agente público:",options:["pode fazer tudo o que a lei não proíbe","atua apenas conforme autorização ou dever jurídico","possui liberdade equivalente à autonomia privada","pode afastar norma por conveniência"],answer:"atua apenas conforme autorização ou dever jurídico",explanation:"Para o particular predomina a liberdade; para a Administração, a atuação exige fundamento no Direito.",basis:"CF/88, art. 37, caput; princípio da legalidade."},
    {id:"1-1-4",q:"A eficiência administrativa permite afastar uma exigência legal quando isso reduzir custos?",options:["sim, sempre que houver economia","sim, se houver urgência","não; eficiência deve ser harmonizada com a legalidade","não, porque eficiência não é princípio constitucional"],answer:"não; eficiência deve ser harmonizada com a legalidade",explanation:"Os princípios administrativos devem ser aplicados conjuntamente; eficiência não autoriza descumprimento da lei.",basis:"CF/88, art. 37, caput."},

    {id:"1-2-2",q:"Qual alternativa reúne somente princípios expressos no caput do art. 37 da Constituição?",options:["legalidade, impessoalidade, moralidade, publicidade e eficiência","finalidade, motivação, razoabilidade, proporcionalidade e eficiência","supremacia, autotutela, publicidade, moralidade e legalidade","continuidade, especialidade, eficiência, publicidade e motivação"],answer:"legalidade, impessoalidade, moralidade, publicidade e eficiência",explanation:"O caput do art. 37 consagra expressamente o conjunto conhecido pelo mnemônico LIMPE.",basis:"CF/88, art. 37, caput."},
    {id:"1-2-3",q:"Os princípios do art. 37, caput, vinculam:",options:["somente o Poder Executivo federal","apenas a Administração direta","a Administração direta e indireta de qualquer dos Poderes da União, Estados, DF e Municípios","somente servidores efetivos"],answer:"a Administração direta e indireta de qualquer dos Poderes da União, Estados, DF e Municípios",explanation:"A própria redação constitucional atribui esse alcance aos princípios administrativos expressos.",basis:"CF/88, art. 37, caput."},
    {id:"1-2-4",q:"A inclusão expressa da eficiência no caput do art. 37 ocorreu com:",options:["a Constituição de 1967","a Emenda Constitucional nº 19/1998","a Lei nº 9.784/1999","a Emenda Constitucional nº 45/2004"],answer:"a Emenda Constitucional nº 19/1998",explanation:"A EC 19/1998 inseriu expressamente a eficiência entre os princípios constitucionais da Administração Pública.",basis:"CF/88, art. 37, caput; EC 19/1998."},

    {id:"1-3-2",q:"Uma autoridade determina prioridade de atendimento a um amigo, sem critério legal. O princípio mais diretamente violado é o da:",options:["publicidade","impessoalidade","continuidade","especialidade"],answer:"impessoalidade",explanation:"A impessoalidade veda privilégios e perseguições baseados em relações pessoais.",basis:"CF/88, art. 37, caput."},
    {id:"1-3-3",q:"A impessoalidade também se manifesta quando a publicidade oficial:",options:["promove nomes e imagens de autoridades","é usada para informar a população sem promoção pessoal","omite sempre o órgão responsável","é divulgada apenas internamente"],answer:"é usada para informar a população sem promoção pessoal",explanation:"A publicidade institucional deve ter caráter educativo, informativo ou de orientação social, sem promoção pessoal.",basis:"CF/88, art. 37, § 1º."},
    {id:"1-3-4",q:"Em concurso público, a adoção de critérios objetivos e previamente definidos concretiza especialmente:",options:["impessoalidade","sigilo absoluto","hierarquia","autotutela"],answer:"impessoalidade",explanation:"Critérios objetivos reduzem favorecimentos pessoais e asseguram tratamento isonômico.",basis:"CF/88, art. 37, caput e II."},

    {id:"1-4-2",q:"A publicidade administrativa é absoluta, sem qualquer possibilidade de sigilo?",options:["sim, porque todo dado estatal deve ser público","não; existem hipóteses legais de restrição de acesso","sim, exceto em processos judiciais","não, porque a publicidade não é princípio constitucional"],answer:"não; existem hipóteses legais de restrição de acesso",explanation:"A publicidade é regra de transparência, mas convive com sigilos e restrições legalmente previstos.",basis:"CF/88, art. 5º, XXXIII; art. 37, caput; Lei 12.527/2011."},
    {id:"1-4-3",q:"Qual situação melhor concretiza o princípio da publicidade?",options:["manter atos administrativos sempre secretos","divulgar atos e informações públicas pelos meios adequados, ressalvado o sigilo legal","promover pessoalmente o gestor","eliminar registros para reduzir burocracia"],answer:"divulgar atos e informações públicas pelos meios adequados, ressalvado o sigilo legal",explanation:"Publicidade envolve transparência, conhecimento e possibilidade de controle da atuação estatal.",basis:"CF/88, art. 37, caput; Lei 12.527/2011."},
    {id:"1-4-4",q:"A publicidade institucional que exalta a figura pessoal do prefeito, com nomes e imagens para autopromoção, viola especialmente:",options:["o art. 37, § 1º, e a impessoalidade","somente a eficiência","somente a continuidade","apenas a especialidade"],answer:"o art. 37, § 1º, e a impessoalidade",explanation:"A Constituição proíbe publicidade oficial que caracterize promoção pessoal de autoridades ou servidores.",basis:"CF/88, art. 37, § 1º."},

    {id:"1-5-2",q:"Um setor reduz o tempo médio de atendimento sem perder qualidade e sem descumprir normas. Essa conduta concretiza principalmente:",options:["eficiência","sigilo","especialidade","tutela"],answer:"eficiência",explanation:"Eficiência envolve melhores resultados, qualidade e uso racional de recursos, respeitados os demais princípios.",basis:"CF/88, art. 37, caput."},
    {id:"1-5-3",q:"A eficiência administrativa deve ser avaliada apenas pela rapidez do serviço?",options:["sim, rapidez é o único critério","não; envolve também qualidade, resultados e uso racional de recursos","sim, desde que haja economia","não, porque eficiência se aplica apenas ao setor privado"],answer:"não; envolve também qualidade, resultados e uso racional de recursos",explanation:"Eficiência não se resume à velocidade; considera desempenho, qualidade e racionalidade administrativa.",basis:"CF/88, art. 37, caput."},
    {id:"1-5-4",q:"Uma medida é muito barata, mas produz serviço de baixa qualidade e retrabalho constante. Sob a ótica da eficiência:",options:["é eficiente porque custa menos","não é necessariamente eficiente, pois custo deve ser relacionado a resultado e qualidade","é eficiente se for rápida","eficiência não considera resultados"],answer:"não é necessariamente eficiente, pois custo deve ser relacionado a resultado e qualidade",explanation:"Economia isolada não basta; eficiência exige resultado adequado com uso racional dos recursos.",basis:"CF/88, art. 37, caput."},

    {id:"1-6-2",q:"Um ato pode ser formalmente compatível com uma regra e ainda assim afrontar a moralidade administrativa?",options:["não, legalidade e moralidade são idênticas","sim, porque moralidade possui conteúdo jurídico próprio ligado à ética pública e boa-fé","não, moralidade é apenas opinião pessoal","sim, mas apenas em contratos privados"],answer:"sim, porque moralidade possui conteúdo jurídico próprio ligado à ética pública e boa-fé",explanation:"A moralidade administrativa é princípio jurídico autônomo e não se reduz ao cumprimento formal de regras.",basis:"CF/88, art. 37, caput."},
    {id:"1-6-3",q:"Servidor utiliza informação obtida no cargo para favorecer negócio particular de familiar. A situação é incompatível especialmente com:",options:["moralidade e impessoalidade","publicidade e continuidade","especialidade e desconcentração","eficiência apenas"],answer:"moralidade e impessoalidade",explanation:"O uso privado da função pública e o favorecimento pessoal afrontam a ética administrativa e a neutralidade da atuação estatal.",basis:"CF/88, art. 37, caput."},
    {id:"1-6-4",q:"A moralidade administrativa deve ser entendida como:",options:["moral pessoal de cada gestor","padrão jurídico de conduta ética compatível com a função pública","mera recomendação sem efeitos jurídicos","princípio aplicável apenas a licitações"],answer:"padrão jurídico de conduta ética compatível com a função pública",explanation:"Moralidade administrativa possui natureza jurídica e orienta a validade e legitimidade da atuação pública.",basis:"CF/88, art. 37, caput."},

    {id:"1-7-2",q:"Uma secretaria municipal integra, em regra:",options:["a Administração Direta do Município","a Administração Indireta como autarquia","uma sociedade de economia mista","uma empresa pública"],answer:"a Administração Direta do Município",explanation:"Secretarias são órgãos da pessoa política Município e não possuem personalidade jurídica própria distinta dele.",basis:"Organização administrativa; material-base fornecido."},
    {id:"1-7-3",q:"A principal diferença entre uma secretaria municipal e uma autarquia é que:",options:["a secretaria integra a pessoa política e a autarquia possui personalidade jurídica própria","ambas possuem personalidade jurídica própria","a secretaria é sempre empresa estatal","a autarquia integra a Administração Direta"],answer:"a secretaria integra a pessoa política e a autarquia possui personalidade jurídica própria",explanation:"Órgãos da Administração Direta não se confundem com entidades da Administração Indireta.",basis:"CF/88, art. 37, XIX; organização administrativa."},
    {id:"1-7-4",q:"Quando a Prefeitura cria internamente novos departamentos dentro de uma secretaria, sem criar nova pessoa jurídica, ocorre:",options:["desconcentração","descentralização","privatização","concessão"],answer:"desconcentração",explanation:"A desconcentração distribui competências entre órgãos da mesma pessoa jurídica.",basis:"Organização administrativa; material-base fornecido."},

    {id:"1-8-2",q:"Um servidor altera a ordem regular de análise de processos para beneficiar um conhecido. A conduta viola diretamente:",options:["impessoalidade","especialidade","continuidade","presunção de legitimidade"],answer:"impessoalidade",explanation:"Alterar procedimento objetivo para favorecer pessoa determinada caracteriza tratamento pessoal indevido.",basis:"CF/88, art. 37, caput."},
    {id:"1-8-3",q:"Aplicar o mesmo critério objetivo a todos os interessados em situações equivalentes favorece:",options:["impessoalidade e isonomia","promoção pessoal","sigilo funcional","hierarquia absoluta"],answer:"impessoalidade e isonomia",explanation:"Critérios uniformes e juridicamente justificáveis reduzem privilégios e discriminações arbitrárias.",basis:"CF/88, arts. 5º, caput, e 37, caput."},
    {id:"1-8-4",q:"A impessoalidade impede que a Administração considere diferenças entre situações juridicamente distintas?",options:["sim, todos devem receber tratamento idêntico em qualquer hipótese","não; diferenças podem ser consideradas quando houver fundamento jurídico objetivo","sim, salvo autorização verbal","não, porque impessoalidade significa ausência de regras"],answer:"não; diferenças podem ser consideradas quando houver fundamento jurídico objetivo",explanation:"Impessoalidade não exige tratamento cego e idêntico, mas veda discriminações arbitrárias e favorecimentos pessoais.",basis:"CF/88, arts. 5º, caput, e 37, caput."},

    {id:"1-9-2",q:"A organização administrativa distribui competências principalmente para:",options:["definir responsabilidades e permitir funcionamento coordenado da Administração","eliminar controles internos","dispensar regras de competência","permitir que qualquer órgão pratique qualquer ato"],answer:"definir responsabilidades e permitir funcionamento coordenado da Administração",explanation:"A estrutura administrativa organiza órgãos, atribuições, fluxos e responsabilidades.",basis:"Organização administrativa; material-base fornecido."},
    {id:"1-9-3",q:"Um órgão público possui personalidade jurídica própria distinta do ente ao qual pertence?",options:["sim, sempre","não; órgão é centro de competências sem personalidade jurídica própria","sim, quando possui orçamento","sim, quando possui chefia"],answer:"não; órgão é centro de competências sem personalidade jurídica própria",explanation:"Órgãos integram a estrutura da pessoa jurídica e não se confundem com entidades administrativas.",basis:"Organização administrativa; material-base fornecido."},
    {id:"1-9-4",q:"A criação de uma autarquia exige, segundo a Constituição:",options:["lei específica","portaria do secretário","decreto autônomo em qualquer caso","contrato administrativo"],answer:"lei específica",explanation:"A Constituição estabelece que autarquia é criada por lei específica.",basis:"CF/88, art. 37, XIX."},

    {id:"1-10-2",q:"Um servidor identifica que não possui competência para decidir determinado requerimento. A providência adequada é:",options:["decidir mesmo assim para ganhar tempo","encaminhar à autoridade ou setor competente, conforme o procedimento","arquivar sem registro","pedir ao interessado que escolha quem decidirá"],answer:"encaminhar à autoridade ou setor competente, conforme o procedimento",explanation:"Competência administrativa deve ser respeitada; o fluxo correto evita vício e assegura regularidade do processo.",basis:"Princípio da legalidade e regras de competência; material-base fornecido."},
    {id:"1-10-3",q:"A competência administrativa pode ser exercida livremente por qualquer servidor do mesmo órgão?",options:["sim, desde que conheça o assunto","não; deve ser exercida por quem tenha atribuição jurídica para o ato","sim, se houver urgência","sim, quando o interessado concordar"],answer:"não; deve ser exercida por quem tenha atribuição jurídica para o ato",explanation:"Competência é elemento jurídico da atuação administrativa e não decorre apenas de conhecimento técnico ou conveniência.",basis:"Princípio da legalidade; organização administrativa; material-base fornecido."},
    {id:"1-10-4",q:"O respeito aos fluxos e competências internas contribui especialmente para:",options:["legalidade, organização e segurança das decisões","eliminação da responsabilidade funcional","dispensa de registros","liberdade absoluta do agente"],answer:"legalidade, organização e segurança das decisões",explanation:"A observância das competências reduz vícios, melhora a rastreabilidade e organiza a atuação administrativa.",basis:"CF/88, art. 37, caput; organização administrativa."}
  ];

  const byId = new Map(DATA.map(q => [q.id, q]));
  let applied = 0;
  replacements.forEach((replacement) => {
    const target = byId.get(replacement.id);
    if (!target) return;
    Object.assign(target, replacement, {theme:"1"});
    applied++;
  });

  window.SAPIENTIA_CONTENT_V2 = { applied, expected: replacements.length };
  console.info(`[Sapientia Content v2] ${applied}/${replacements.length} questões substituídas.`);
})();