/* Sapientia — revisão global v3
   Adiciona questões inéditas e mais desafiadoras em TODOS os temas 2 a 8.
   Deve ser carregado depois dos módulos de conteúdo existentes e antes do auditor.
*/
(() => {
  if (typeof DATA === "undefined" || !Array.isArray(DATA)) return;

  const additions = [
    // Tema 2 — Rotinas Administrativas e Gestão de Documentos
    {id:"2-v3-01",theme:"2",q:"Em gestão documental, qual medida reduz mais diretamente o risco de extravio de um processo físico?",options:["registrar movimentações e responsáveis por cada tramitação","retirar a identificação externa do processo","armazenar todos os processos sem classificação","dispensar protocolo quando o setor for pequeno"],answer:"registrar movimentações e responsáveis por cada tramitação",explanation:"A rastreabilidade documental depende do registro de tramitação, permitindo identificar onde o processo esteve e quem o recebeu.",basis:"Gestão documental e rotinas administrativas."},
    {id:"2-v3-02",theme:"2",q:"Ao receber um documento destinado a outro setor, a conduta administrativa mais adequada é:",options:["alterar o conteúdo antes do encaminhamento","registrar o recebimento e encaminhar ao setor competente","arquivar definitivamente sem análise","devolver ao remetente em qualquer hipótese"],answer:"registrar o recebimento e encaminhar ao setor competente",explanation:"O fluxo documental deve preservar rastreabilidade, integridade e encaminhamento ao responsável pela matéria.",basis:"Rotinas de protocolo e tramitação documental."},
    {id:"2-v3-03",theme:"2",q:"A classificação de documentos por assunto contribui principalmente para:",options:["localização e recuperação da informação","eliminação automática dos documentos","dispensa de controle de acesso","substituição de qualquer tabela de temporalidade"],answer:"localização e recuperação da informação",explanation:"A classificação organiza o acervo e facilita busca, recuperação, controle e destinação documental.",basis:"Gestão documental."},
    {id:"2-v3-04",theme:"2",q:"Em uma rotina de protocolo, o número atribuído ao documento serve principalmente para:",options:["rastrear e individualizar sua tramitação","definir automaticamente seu conteúdo","dispensar a identificação do interessado","eliminar a necessidade de registro de movimentações"],answer:"rastrear e individualizar sua tramitação",explanation:"O número de protocolo funciona como identificador para acompanhamento e controle do documento ou processo.",basis:"Rotinas de protocolo."},
    {id:"2-v3-05",theme:"2",q:"Quando um documento possui prazo de guarda definido, sua eliminação deve ocorrer:",options:["imediatamente após o uso","apenas conforme critérios e procedimentos de gestão documental aplicáveis","sempre ao final do ano","sempre que faltar espaço físico"],answer:"apenas conforme critérios e procedimentos de gestão documental aplicáveis",explanation:"A destinação documental deve observar critérios previamente definidos e não pode depender apenas de conveniência momentânea.",basis:"Gestão documental e temporalidade."},

    // Tema 3 — Atendimento ao Público e Comunicação
    {id:"3-v3-01",theme:"3",q:"Um cidadão apresenta reclamação de forma exaltada. Qual conduta tende a produzir o atendimento mais adequado?",options:["interrompê-lo imediatamente","ouvir, esclarecer fatos e responder com objetividade e respeito","responder no mesmo tom","encerrar o atendimento sem registro"],answer:"ouvir, esclarecer fatos e responder com objetividade e respeito",explanation:"Escuta ativa, respeito e comunicação clara ajudam a compreender a demanda e reduzem conflitos.",basis:"Atendimento ao público e comunicação interpessoal."},
    {id:"3-v3-02",theme:"3",q:"Na comunicação administrativa, uma mensagem tecnicamente correta pode ser ineficaz quando:",options:["não considera o nível de compreensão do destinatário","usa linguagem clara","apresenta informação objetiva","organiza as ideias de modo lógico"],answer:"não considera o nível de compreensão do destinatário",explanation:"Comunicação eficaz exige adaptação da linguagem ao receptor, sem perder precisão.",basis:"Comunicação administrativa."},
    {id:"3-v3-03",theme:"3",q:"Quando o atendente confirma com o cidadão o que entendeu da solicitação, ele está usando uma técnica de:",options:["checagem de compreensão","interrupção","persuasão coercitiva","comunicação unilateral"],answer:"checagem de compreensão",explanation:"Reformular ou confirmar o pedido reduz ruídos e erros de interpretação.",basis:"Atendimento ao público e comunicação."},
    {id:"3-v3-04",theme:"3",q:"Em atendimento presencial, qual comportamento é inadequado?",options:["manter postura respeitosa","explicar procedimentos com clareza","expor dados pessoais de outro usuário para justificar uma decisão","registrar corretamente a demanda"],answer:"expor dados pessoais de outro usuário para justificar uma decisão",explanation:"O atendimento deve respeitar privacidade, sigilo e proteção de informações de terceiros.",basis:"Ética no atendimento e proteção de informações."},
    {id:"3-v3-05",theme:"3",q:"A comunicação assertiva caracteriza-se por:",options:["expressar informações e limites com clareza e respeito","evitar qualquer posicionamento","impor a opinião pela autoridade","usar linguagem ambígua para evitar conflitos"],answer:"expressar informações e limites com clareza e respeito",explanation:"Assertividade combina clareza, objetividade e respeito, sem agressividade ou passividade.",basis:"Comunicação interpessoal."},

    // Tema 4 — Apoio Administrativo e Logística
    {id:"4-v3-01",theme:"4",q:"O estoque de segurança tem como principal finalidade:",options:["absorver variações de consumo ou atraso de reposição","substituir todo o estoque operacional","eliminar inventários","aumentar indefinidamente a quantidade armazenada"],answer:"absorver variações de consumo ou atraso de reposição",explanation:"O estoque de segurança reduz o risco de falta diante de incertezas na demanda ou no tempo de reposição.",basis:"Noções de administração de materiais."},
    {id:"4-v3-02",theme:"4",q:"Se um material tem consumo médio de 20 unidades por dia e o prazo de reposição é de 5 dias, sem estoque de segurança, o ponto de reposição é de:",options:["25 unidades","50 unidades","100 unidades","200 unidades"],answer:"100 unidades",explanation:"Ponto de reposição = consumo médio diário × tempo de reposição = 20 × 5 = 100.",basis:"Gestão de estoques."},
    {id:"4-v3-03",theme:"4",q:"Qual prática melhora a confiabilidade do controle de estoque?",options:["registrar entradas e saídas no momento em que ocorrem","ajustar saldos apenas uma vez por ano","dispensar conferência física","misturar materiais semelhantes sem identificação"],answer:"registrar entradas e saídas no momento em que ocorrem",explanation:"Registros tempestivos reduzem divergências entre estoque físico e sistema de controle.",basis:"Administração de materiais e almoxarifado."},
    {id:"4-v3-04",theme:"4",q:"No método PEPS/FIFO, considera-se que:",options:["os primeiros itens que entram são os primeiros que saem","os últimos itens que entram são os primeiros que saem","todos os itens saem ao mesmo tempo","a ordem de entrada é irrelevante"],answer:"os primeiros itens que entram são os primeiros que saem",explanation:"PEPS significa primeiro que entra, primeiro que sai; em inglês, FIFO.",basis:"Gestão de estoques."},
    {id:"4-v3-05",theme:"4",q:"A realização de inventário físico serve principalmente para:",options:["comparar a quantidade existente com os registros de controle","substituir qualquer registro de entrada e saída","dispensar identificação patrimonial","eliminar a necessidade de armazenamento adequado"],answer:"comparar a quantidade existente com os registros de controle",explanation:"O inventário ajuda a identificar diferenças, perdas, erros de registro e necessidades de ajuste.",basis:"Controle de materiais e patrimônio."},

    // Tema 5 — Informática Básica
    {id:"5-v3-01",theme:"5",q:"Em uma planilha, qual referência permanece totalmente fixa ao copiar a fórmula para outra célula?",options:["A1","$A$1","A$1","$A1"],answer:"$A$1",explanation:"A referência absoluta fixa simultaneamente coluna e linha.",basis:"Planilhas eletrônicas; referências relativas e absolutas."},
    {id:"5-v3-02",theme:"5",q:"Qual prática aumenta a segurança de uma conta institucional?",options:["usar a mesma senha em todos os serviços","ativar autenticação em múltiplos fatores","compartilhar a senha com colegas","anotar a senha em local público"],answer:"ativar autenticação em múltiplos fatores",explanation:"A autenticação em múltiplos fatores reduz o risco de acesso indevido mesmo se a senha for comprometida.",basis:"Segurança da informação."},
    {id:"5-v3-03",theme:"5",q:"Um arquivo recebido por e-mail pede habilitação de macros para visualizar uma suposta nota fiscal. A conduta mais segura é:",options:["habilitar imediatamente","verificar a origem e evitar executar conteúdo ativo não confiável","reenviar para vários colegas testarem","desativar o antivírus"],answer:"verificar a origem e evitar executar conteúdo ativo não confiável",explanation:"Macros podem executar código malicioso; anexos inesperados devem ser verificados antes de qualquer execução.",basis:"Segurança da informação e correio eletrônico."},
    {id:"5-v3-04",theme:"5",q:"No contexto de navegadores, o cache é usado principalmente para:",options:["armazenar temporariamente recursos para acelerar acessos posteriores","criptografar todos os arquivos do computador","substituir backups","bloquear automaticamente todo malware"],answer:"armazenar temporariamente recursos para acelerar acessos posteriores",explanation:"O cache guarda cópias temporárias de recursos, podendo reduzir tempo e tráfego em acessos futuros.",basis:"Navegação na internet."},
    {id:"5-v3-05",theme:"5",q:"Qual alternativa descreve corretamente um backup incremental?",options:["copia apenas dados alterados desde o último backup relevante","copia sempre todos os arquivos","é apenas uma sincronização sem histórico","elimina a necessidade de restauração"],answer:"copia apenas dados alterados desde o último backup relevante",explanation:"Backups incrementais armazenam alterações desde o backup anterior, reduzindo volume e tempo de cópia.",basis:"Segurança da informação e backups."},

    // Tema 6 — Ética, Legislação e Transparência
    {id:"6-v3-01",theme:"6",q:"Pela Lei de Acesso à Informação, a publicidade é tratada como:",options:["regra geral, sendo o sigilo exceção","exceção, sendo o sigilo a regra","opção discricionária do gestor","medida aplicável apenas à União"],answer:"regra geral, sendo o sigilo exceção",explanation:"A LAI adota a publicidade como regra e o sigilo como exceção.",basis:"Lei 12.527/2011, art. 3º, I."},
    {id:"6-v3-02",theme:"6",q:"Transparência ativa corresponde à:",options:["divulgação espontânea de informações de interesse coletivo, independentemente de pedido","resposta apenas após requerimento formal","divulgação exclusiva de dados sigilosos","eliminação de canais de acesso"],answer:"divulgação espontânea de informações de interesse coletivo, independentemente de pedido",explanation:"Órgãos e entidades devem divulgar proativamente informações de interesse coletivo ou geral.",basis:"Lei 12.527/2011, art. 8º."},
    {id:"6-v3-03",theme:"6",q:"Ao formular pedido de acesso à informação, o interessado precisa apresentar os motivos do pedido?",options:["sim, sempre","não, são vedadas exigências relativas aos motivos da solicitação","sim, quando a informação for pública","somente se o pedido for eletrônico"],answer:"não, são vedadas exigências relativas aos motivos da solicitação",explanation:"A LAI veda exigir do requerente justificativa sobre o motivo do pedido.",basis:"Lei 12.527/2011, art. 10, § 3º."},
    {id:"6-v3-04",theme:"6",q:"Se a informação solicitada estiver disponível, a LAI determina que o acesso deve ser concedido:",options:["imediatamente, quando possível","somente após 30 dias","apenas mediante pagamento de taxa","apenas após autorização judicial"],answer:"imediatamente, quando possível",explanation:"O órgão deve autorizar ou conceder acesso imediato à informação disponível.",basis:"Lei 12.527/2011, art. 11, caput."},
    {id:"6-v3-05",theme:"6",q:"Quando não for possível conceder acesso imediato, o prazo legal geral para resposta é de até:",options:["5 dias","10 dias","20 dias","60 dias"],answer:"20 dias",explanation:"A LAI estabelece prazo de até 20 dias, prorrogável por mais 10 mediante justificativa expressa.",basis:"Lei 12.527/2011, art. 11, §§ 1º e 2º."},

    // Tema 7 — Língua Portuguesa
    {id:"7-v3-01",theme:"7",q:"Assinale a alternativa em que o uso da crase está correto:",options:["O servidor dirigiu-se à chefia para esclarecer a dúvida.","O relatório foi entregue à partir das oito horas.","A reunião ocorrerá de segunda à sexta.","O documento foi enviado à todos os setores."],answer:"O servidor dirigiu-se à chefia para esclarecer a dúvida.",explanation:"Há fusão da preposição exigida por 'dirigir-se a' com o artigo feminino de 'a chefia'.",basis:"Língua Portuguesa — regência e crase."},
    {id:"7-v3-02",theme:"7",q:"Em 'Os documentos que chegaram ontem serão analisados hoje', a oração 'que chegaram ontem' é:",options:["subordinada adjetiva restritiva","subordinada adjetiva explicativa","subordinada substantiva subjetiva","coordenada sindética explicativa"],answer:"subordinada adjetiva restritiva",explanation:"Sem vírgulas, a oração restringe o conjunto de documentos aos que chegaram ontem.",basis:"Língua Portuguesa — período composto."},
    {id:"7-v3-03",theme:"7",q:"Assinale a frase com concordância verbal correta:",options:["Fazem dois anos que o sistema foi implantado.","Houveram muitos pedidos ontem.","Existe diversos processos pendentes.","Devem existir soluções para o problema."],answer:"Devem existir soluções para o problema.",explanation:"O verbo 'existir' concorda com o sujeito 'soluções'; já 'fazer' indicando tempo e 'haver' no sentido de existir são impessoais.",basis:"Língua Portuguesa — concordância verbal."},
    {id:"7-v3-04",theme:"7",q:"Na frase 'Embora estivesse cansado, o servidor concluiu o relatório', a conjunção 'embora' expressa ideia de:",options:["causa","concessão","condição","conclusão"],answer:"concessão",explanation:"A oração concessiva apresenta um fato que poderia dificultar, mas não impede a ocorrência da ação principal.",basis:"Língua Portuguesa — relações semânticas entre orações."},
    {id:"7-v3-05",theme:"7",q:"Assinale a alternativa em que a colocação pronominal está de acordo com a norma-padrão:",options:["Não me informaram o número do processo.","Me não informaram o número do processo.","Jamais informaram-me o número do processo.","Quem entregou-me o documento?"],answer:"Não me informaram o número do processo.",explanation:"Palavras negativas atraem o pronome átono, exigindo próclise.",basis:"Língua Portuguesa — colocação pronominal."},
    {id:"7-v3-06",theme:"7",q:"Em 'O chefe solicitou que o servidor revisasse o ofício', o termo 'que o servidor revisasse o ofício' exerce função de:",options:["oração subordinada substantiva objetiva direta","oração subordinada adverbial causal","oração subordinada adjetiva restritiva","oração coordenada adversativa"],answer:"oração subordinada substantiva objetiva direta",explanation:"A oração completa o sentido do verbo transitivo direto 'solicitou'.",basis:"Língua Portuguesa — sintaxe do período composto."},
    {id:"7-v3-07",theme:"7",q:"Assinale a alternativa em que a pontuação está adequada:",options:["Senhores servidores, encaminhem os relatórios até amanhã.","Senhores, servidores encaminhem os relatórios até amanhã.","Senhores servidores encaminhem, os relatórios até amanhã.","Senhores servidores encaminhem os relatórios, até amanhã."],answer:"Senhores servidores, encaminhem os relatórios até amanhã.",explanation:"O vocativo 'Senhores servidores' deve ser isolado por vírgula.",basis:"Língua Portuguesa — pontuação."},
    {id:"7-v3-08",theme:"7",q:"Na frase 'O processo foi arquivado porque o prazo havia terminado', a oração introduzida por 'porque' expressa:",options:["causa","consequência","comparação","finalidade"],answer:"causa",explanation:"A oração explica a razão do arquivamento.",basis:"Língua Portuguesa — relações semânticas."},
    {id:"7-v3-09",theme:"7",q:"Assinale a opção em que há sentido denotativo:",options:["A notícia caiu como uma bomba.","O servidor abriu a porta da sala.","A chefia engoliu a reclamação.","O prazo voou."],answer:"O servidor abriu a porta da sala.",explanation:"O verbo 'abrir' e o substantivo 'porta' são empregados em sentido literal.",basis:"Língua Portuguesa — denotação e conotação."},
    {id:"7-v3-10",theme:"7",q:"Em 'Precisam-se de servidores experientes', a construção está:",options:["incorreta; o correto é 'Precisa-se de servidores experientes'","correta, pois o verbo concorda com 'servidores'","correta apenas na linguagem informal","incorreta; o correto é 'Precisam de-se servidores experientes'"],answer:"incorreta; o correto é 'Precisa-se de servidores experientes'",explanation:"Com verbo transitivo indireto acompanhado de índice de indeterminação do sujeito, o verbo permanece na 3ª pessoa do singular.",basis:"Língua Portuguesa — concordância e partícula 'se'."},

    // Tema 8 — Raciocínio Lógico e Resolução de Problemas
    {id:"8-v3-01",theme:"8",q:"A negação de 'Todos os processos foram concluídos' é:",options:["Nenhum processo foi concluído","Pelo menos um processo não foi concluído","Todos os processos não foram concluídos","Alguns processos foram concluídos"],answer:"Pelo menos um processo não foi concluído",explanation:"A negação de uma proposição universal afirmativa é uma proposição existencial negativa.",basis:"Lógica proposicional e quantificadores."},
    {id:"8-v3-02",theme:"8",q:"Se 'Se o sistema falha, então o atendimento atrasa' é verdadeira e o atendimento não atrasou, conclui-se logicamente que:",options:["o sistema falhou","o sistema não falhou","o sistema pode ter falhado ou não","o atendimento falhou"],answer:"o sistema não falhou",explanation:"Aplicação de modus tollens: p→q e ¬q implicam ¬p.",basis:"Lógica proposicional."},
    {id:"8-v3-03",theme:"8",q:"Uma fila possui 5 pessoas distintas. De quantas maneiras elas podem ocupar as 5 posições?",options:["25","60","120","625"],answer:"120",explanation:"Trata-se de uma permutação simples: 5! = 120.",basis:"Análise combinatória."},
    {id:"8-v3-04",theme:"8",q:"Um setor resolve 3/5 de 200 processos. Quantos processos foram resolvidos?",options:["80","100","120","150"],answer:"120",explanation:"3/5 de 200 = 200 × 3 ÷ 5 = 120.",basis:"Frações e proporcionalidade."},
    {id:"8-v3-05",theme:"8",q:"Se um valor aumenta de 80 para 100, o aumento percentual é de:",options:["20%","25%","40%","80%"],answer:"25%",explanation:"O aumento foi 20; 20/80 = 0,25 = 25%.",basis:"Porcentagem."},
    {id:"8-v3-06",theme:"8",q:"A proposição 'p ou q' é falsa somente quando:",options:["p e q são ambas falsas","p e q são ambas verdadeiras","p é verdadeira e q é falsa","p é falsa e q é verdadeira"],answer:"p e q são ambas falsas",explanation:"Na disjunção inclusiva, basta uma proposição verdadeira para o resultado ser verdadeiro.",basis:"Tabela-verdade."},
    {id:"8-v3-07",theme:"8",q:"Em uma urna há 3 bolas vermelhas e 2 azuis. Retirando uma bola ao acaso, a probabilidade de sair azul é:",options:["2/3","2/5","3/5","1/2"],answer:"2/5",explanation:"Há 2 resultados favoráveis em 5 possíveis.",basis:"Probabilidade básica."},
    {id:"8-v3-08",theme:"8",q:"A média aritmética de 6, 8, 10 e 12 é:",options:["8","9","10","11"],answer:"9",explanation:"(6+8+10+12)/4 = 36/4 = 9.",basis:"Média aritmética."},
    {id:"8-v3-09",theme:"8",q:"Se 4 servidores executam uma tarefa em 6 dias, mantendo produtividade constante, 8 servidores executariam a mesma tarefa em:",options:["2 dias","3 dias","6 dias","12 dias"],answer:"3 dias",explanation:"Grandezas inversamente proporcionais: dobrando o número de servidores, o tempo cai pela metade.",basis:"Regra de três inversa."},
    {id:"8-v3-10",theme:"8",q:"Considere a sequência 2, 6, 18, 54, ... O próximo termo é:",options:["108","126","162","216"],answer:"162",explanation:"Cada termo é o anterior multiplicado por 3.",basis:"Sequências numéricas."}
  ];

  const existing = new Set(DATA.map(q => q.id));
  let added = 0;
  additions.forEach(q => {
    if (existing.has(q.id)) return;
    DATA.push(q);
    existing.add(q.id);
    added++;
  });

  window.SAPIENTIA_ALL_THEMES_V3 = {added, expected:additions.length};
  console.info(`[Sapientia v3] ${added}/${additions.length} questões globais adicionadas.`);
})();
