/* Sapientia — expansão de conteúdo v2 para temas 2 a 6.
   Acrescenta 25 questões inéditas e distintas (5 por tema).
   Deve ser carregado após DATA e antes do módulo de auditoria.
*/
(() => {
  if (typeof DATA === 'undefined' || !Array.isArray(DATA)) return;

  const extra = [
    {id:'2-v2-41',theme:'2',q:'Ao receber um documento externo, qual providência favorece a rastreabilidade administrativa?',options:['registrar o recebimento com data, identificação e origem','encaminhar sem qualquer registro','arquivar imediatamente sem leitura','eliminar o envelope e o documento'],answer:'registrar o recebimento com data, identificação e origem',explanation:'O protocolo permite identificar o ingresso do documento e acompanhar sua tramitação.',basis:'Material-base de Rotinas Administrativas e Gestão de Documentos.'},
    {id:'2-v2-42',theme:'2',q:'Durante a tramitação de um processo, a movimentação entre setores deve ser:',options:['registrada de forma que seja possível saber onde o processo se encontra','feita apenas verbalmente','omitida para reduzir burocracia','registrada somente ao final'],answer:'registrada de forma que seja possível saber onde o processo se encontra',explanation:'O controle de tramitação evita extravios e permite localizar o processo.',basis:'Material-base de Rotinas Administrativas e Gestão de Documentos.'},
    {id:'2-v2-43',theme:'2',q:'Qual prática é mais adequada ao arquivamento de documentos?',options:['utilizar critérios padronizados de classificação e ordenação','guardar documentos sem critério definido','misturar documentos correntes e eliminados','arquivar apenas pela cor do papel'],answer:'utilizar critérios padronizados de classificação e ordenação',explanation:'A padronização facilita localização, recuperação e controle documental.',basis:'Material-base de Rotinas Administrativas e Gestão de Documentos.'},
    {id:'2-v2-44',theme:'2',q:'Um documento necessário para atividades frequentes e consultas rotineiras é, em regra, mantido em arquivo:',options:['corrente','permanente obrigatoriamente','eliminado','histórico apenas'],answer:'corrente',explanation:'Documentos em uso frequente permanecem na fase corrente do ciclo documental.',basis:'Material-base de Rotinas Administrativas e Gestão de Documentos.'},
    {id:'2-v2-45',theme:'2',q:'Antes de eliminar documentos administrativos, a conduta mais adequada é:',options:['observar os critérios e prazos de guarda aplicáveis','eliminar tudo ao fim do ano','eliminar apenas os documentos volumosos','pedir autorização verbal a qualquer colega'],answer:'observar os critérios e prazos de guarda aplicáveis',explanation:'A eliminação deve respeitar regras de gestão documental e temporalidade.',basis:'Material-base de Rotinas Administrativas e Gestão de Documentos.'},

    {id:'3-v2-41',theme:'3',q:'No atendimento ao cidadão, uma resposta tecnicamente correta, mas dada de forma hostil, é adequada?',options:['não; qualidade do atendimento envolve conteúdo e forma de comunicação','sim, porque apenas a informação importa','sim, se o setor estiver movimentado','não, porque o servidor nunca pode discordar do cidadão'],answer:'não; qualidade do atendimento envolve conteúdo e forma de comunicação',explanation:'Cordialidade, clareza e respeito integram o atendimento de qualidade.',basis:'Material-base de Atendimento ao Público e Comunicação.'},
    {id:'3-v2-42',theme:'3',q:'Ao atender uma pessoa que apresenta uma reclamação, a primeira atitude recomendável é:',options:['ouvir com atenção e compreender a demanda antes de responder','interromper para ganhar tempo','encaminhar sem ouvir o relato','contestar imediatamente'],answer:'ouvir com atenção e compreender a demanda antes de responder',explanation:'A escuta ativa reduz ruídos e ajuda a identificar corretamente a necessidade do usuário.',basis:'Material-base de Atendimento ao Público e Comunicação.'},
    {id:'3-v2-43',theme:'3',q:'Em comunicação administrativa, linguagem clara significa:',options:['usar termos compreensíveis e evitar ambiguidades desnecessárias','usar sempre linguagem rebuscada','eliminar informações essenciais','utilizar jargão mesmo quando o público não o conhece'],answer:'usar termos compreensíveis e evitar ambiguidades desnecessárias',explanation:'Clareza favorece compreensão e reduz retrabalho no atendimento.',basis:'Material-base de Atendimento ao Público e Comunicação.'},
    {id:'3-v2-44',theme:'3',q:'Se o atendente não souber responder com segurança a uma dúvida do cidadão, deve:',options:['buscar a informação correta ou encaminhar ao setor competente','inventar uma resposta plausível','encerrar o atendimento sem orientação','atribuir a resposta a outro servidor sem verificar'],answer:'buscar a informação correta ou encaminhar ao setor competente',explanation:'Informações imprecisas comprometem a confiança e a qualidade do serviço.',basis:'Material-base de Atendimento ao Público e Comunicação.'},
    {id:'3-v2-45',theme:'3',q:'Em uma comunicação telefônica institucional, é recomendável:',options:['identificar o órgão ou setor e falar de forma objetiva e cordial','atender sem identificação','usar abreviações incompreensíveis','encerrar a ligação assim que a pessoa demonstrar dúvida'],answer:'identificar o órgão ou setor e falar de forma objetiva e cordial',explanation:'Identificação, objetividade e cordialidade são práticas básicas de atendimento telefônico.',basis:'Material-base de Atendimento ao Público e Comunicação.'},

    {id:'4-v2-41',theme:'4',q:'No controle de estoque, registrar entradas e saídas serve principalmente para:',options:['conhecer saldos e apoiar reposições e prestação de contas','aumentar o consumo de materiais','dispensar inventários','eliminar a identificação dos itens'],answer:'conhecer saldos e apoiar reposições e prestação de contas',explanation:'Movimentações registradas permitem controle físico e administrativo do estoque.',basis:'Material-base de Atividades de Apoio Administrativo e Logística.'},
    {id:'4-v2-42',theme:'4',q:'Ao receber materiais no almoxarifado, é adequado conferir:',options:['quantidade, especificação e condições do material recebido','somente a cor da embalagem','apenas o nome do entregador','nada, se houver nota fiscal'],answer:'quantidade, especificação e condições do material recebido',explanation:'A conferência reduz divergências entre pedido, entrega e registro.',basis:'Material-base de Atividades de Apoio Administrativo e Logística.'},
    {id:'4-v2-43',theme:'4',q:'Um estoque excessivo pode ser indesejável porque:',options:['imobiliza recursos e pode aumentar perdas e obsolescência','sempre reduz custos','elimina a necessidade de controle','impede qualquer falta de material'],answer:'imobiliza recursos e pode aumentar perdas e obsolescência',explanation:'A gestão de estoques busca equilíbrio entre disponibilidade e custos.',basis:'Material-base de Atividades de Apoio Administrativo e Logística.'},
    {id:'4-v2-44',theme:'4',q:'Na organização de um evento institucional, uma lista de verificação é útil porque:',options:['ajuda a acompanhar tarefas, responsáveis e itens necessários','substitui todo planejamento','dispensa comunicação entre equipes','serve apenas para registrar despesas'],answer:'ajuda a acompanhar tarefas, responsáveis e itens necessários',explanation:'Checklists reduzem esquecimentos e facilitam coordenação logística.',basis:'Material-base de Atividades de Apoio Administrativo e Logística.'},
    {id:'4-v2-45',theme:'4',q:'Quando um equipamento apresenta defeito, a conduta administrativa mais adequada é:',options:['registrar a ocorrência e encaminhar conforme o procedimento de manutenção','continuar usando até parar totalmente','descartar sem registro','levar para casa para consertar'],answer:'registrar a ocorrência e encaminhar conforme o procedimento de manutenção',explanation:'Registro e fluxo adequado preservam controle patrimonial e continuidade das atividades.',basis:'Material-base de Atividades de Apoio Administrativo e Logística.'},

    {id:'5-v2-41',theme:'5',q:'Ao receber por e-mail um arquivo inesperado de remetente desconhecido, a prática mais segura é:',options:['não abrir imediatamente e verificar a legitimidade da mensagem','abrir para descobrir o conteúdo','encaminhar a todos os colegas','desativar o antivírus antes de abrir'],answer:'não abrir imediatamente e verificar a legitimidade da mensagem',explanation:'Anexos inesperados podem conter malware ou integrar tentativas de phishing.',basis:'Boas práticas de segurança da informação; material-base de Informática.'},
    {id:'5-v2-42',theme:'5',q:'Em uma planilha, uma fórmula normalmente começa com:',options:['=','@ obrigatoriamente','#','&'],answer:'=',explanation:'Aplicativos de planilha utilizam o sinal de igualdade para iniciar fórmulas.',basis:'Material-base de Informática Básica Aplicada ao Serviço Público.'},
    {id:'5-v2-43',theme:'5',q:'Qual prática reduz o risco de perda de arquivos importantes?',options:['manter cópias de segurança adequadas','salvar sempre em um único local sem backup','renomear todos os arquivos como documento','desligar atualizações do sistema'],answer:'manter cópias de segurança adequadas',explanation:'Backups permitem recuperação em caso de falha, exclusão ou incidente.',basis:'Material-base de Informática Básica Aplicada ao Serviço Público.'},
    {id:'5-v2-44',theme:'5',q:'Uma senha forte deve, preferencialmente:',options:['ser longa, difícil de adivinhar e não reutilizada em vários serviços','conter apenas o primeiro nome do usuário','ser igual em todos os sistemas','ficar anotada publicamente ao lado do computador'],answer:'ser longa, difícil de adivinhar e não reutilizada em vários serviços',explanation:'Senhas únicas e robustas reduzem o impacto de vazamentos e tentativas de adivinhação.',basis:'Boas práticas de segurança da informação; material-base de Informática.'},
    {id:'5-v2-45',theme:'5',q:'Ao organizar arquivos digitais de um setor, nomes padronizados e pastas bem definidas ajudam a:',options:['localizar documentos com mais rapidez e reduzir duplicidades','impedir qualquer compartilhamento','substituir todos os backups','eliminar a necessidade de controle de acesso'],answer:'localizar documentos com mais rapidez e reduzir duplicidades',explanation:'Padronização de nomes e diretórios melhora a organização e recuperação da informação.',basis:'Material-base de Informática Básica Aplicada ao Serviço Público.'},

    {id:'6-v2-41',theme:'6',q:'Segundo a Lei de Acesso à Informação, a divulgação de informações de interesse coletivo ou geral, independentemente de pedido, corresponde à chamada:',options:['transparência ativa','transparência passiva','reserva legal','classificação automática'],answer:'transparência ativa',explanation:'A LAI determina a divulgação espontânea de informações de interesse coletivo ou geral.',basis:'Lei 12.527/2011, art. 8º.'},
    {id:'6-v2-42',theme:'6',q:'Um pedido de acesso à informação de interesse público pode exigir que o cidadão apresente a razão pela qual deseja a informação?',options:['não; não se pode exigir motivação do pedido','sim, sempre','sim, apenas em municípios','sim, se o órgão preferir'],answer:'não; não se pode exigir motivação do pedido',explanation:'A LAI veda exigências relativas aos motivos determinantes da solicitação de informação de interesse público.',basis:'Lei 12.527/2011, art. 10.'},
    {id:'6-v2-43',theme:'6',q:'Se a informação solicitada estiver disponível, a LAI estabelece como regra que o acesso seja:',options:['imediato','sempre em 30 dias','somente após recurso','apenas mediante pagamento'],answer:'imediato',explanation:'O art. 11 determina que o órgão autorize ou conceda acesso imediato à informação disponível.',basis:'Lei 12.527/2011, art. 11, caput.'},
    {id:'6-v2-44',theme:'6',q:'Quando não for possível conceder acesso imediato, o prazo geral previsto na LAI para resposta é de até:',options:['20 dias','5 dias','60 dias','90 dias'],answer:'20 dias',explanation:'A LAI prevê prazo não superior a 20 dias, observadas as hipóteses e condições legais de prorrogação.',basis:'Lei 12.527/2011, art. 11, § 1º.'},
    {id:'6-v2-45',theme:'6',q:'Negar acesso a uma informação pública sem apresentar fundamento adequado é compatível com a LAI?',options:['não; a negativa deve observar fundamento e procedimento legal','sim, porque o órgão não precisa justificar','sim, se o pedido for eletrônico','sim, sempre que houver muito trabalho no setor'],answer:'não; a negativa deve observar fundamento e procedimento legal',explanation:'A LAI exige tratamento fundamentado das negativas e prevê responsabilização em determinadas hipóteses.',basis:'Lei 12.527/2011, arts. 7º, 11 e 32.'}
  ];

  const existing = new Set(DATA.map(q => q.id));
  let added = 0;
  extra.forEach(q => { if (!existing.has(q.id)) { DATA.push(q); existing.add(q.id); added++; } });
  window.SAPIENTIA_OTHER_THEMES_V2 = {added, expected: extra.length};
  console.info(`[Sapientia Other Themes v2] ${added}/${extra.length} questões adicionadas.`);
})();
