/* Sapientia — aprimoramentos visuais não destrutivos */
(() => {
  const themePalette=[['📘','#536dfe'],['🗂️','#00a7a5'],['🤝','#f59e0b'],['📦','#8b5cf6'],['💻','#0ea5e9'],['⚖️','#ef6c6c'],['✍️','#ec4899'],['🧠','#22a06b']];
  function enhanceHeader(){const wrap=document.querySelector('header .wrap');if(!wrap||wrap.querySelector('.sapientia-kicker'))return;const kicker=document.createElement('div');kicker.className='sapientia-kicker';kicker.textContent='🎓 Sapientia • Plataforma de Estudos';wrap.insertBefore(kicker,wrap.firstChild);const chips=document.createElement('div');chips.className='sapientia-hero-row';chips.innerHTML='<span class="hero-chip">📚 questões por tema</span><span class="hero-chip">🎯 treino aleatório</span><span class="hero-chip">📈 desempenho salvo</span>';wrap.appendChild(chips)}
  function enhanceHome(){const themes=document.getElementById('themes');if(!themes)return;if(!document.querySelector('.sapientia-section-title')){const title=document.createElement('div');title.className='sapientia-section-title';title.innerHTML='<div><h2>Escolha uma matéria</h2><p>Treine por assunto e acompanhe sua evolução.</p></div><p>📌 clique em um cartão para começar</p>';themes.parentNode.insertBefore(title,themes)}}
  function enhanceCards(){document.querySelectorAll('#themes .theme').forEach((card,index)=>{const[icon,color]=themePalette[index%themePalette.length];card.style.setProperty('--theme-color',color);if(!card.querySelector('.theme-icon')){const el=document.createElement('div');el.className='theme-icon';el.textContent=icon;const pill=card.querySelector('.pill');if(pill)pill.insertAdjacentElement('afterend',el);else card.prepend(el)}const p=card.querySelector('p');if(p&&!card.querySelector('.theme-progress')){const match=(p.textContent||'').match(/(\d+)%/);const pct=match?Math.max(0,Math.min(100,Number(match[1]))):0;const bar=document.createElement('div');bar.className='theme-progress';bar.innerHTML=`<span style="width:${pct}%"></span>`;p.insertAdjacentElement('afterend',bar)}})}
  function enhanceQuiz(){const select=document.getElementById('count');if(select&&!select.getAttribute('aria-label'))select.setAttribute('aria-label','Quantidade de questões do treino')}
  function run(){enhanceHeader();enhanceHome();enhanceCards();enhanceQuiz()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
  const observer=new MutationObserver(()=>enhanceCards());const themes=document.getElementById('themes');if(themes)observer.observe(themes,{childList:true});
})();
