/* Sapientia — dashboard escolar moderno */
(() => {
  const themePalette=[['🏛️','#2f80ed'],['📄','#00a896'],['👥','#ff8a34'],['📦','#8b5cf6'],['🖥️','#ff5a63'],['⚖️','#f5b51b'],['🔤','#ec5ca8'],['🧠','#48b89f']];
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const safeParse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}};
  function stats(){return safeParse(localStorage.getItem('quizStats')||localStorage.getItem('stats')||'{}',{});}
  function calc(){const s=stats();let a=0,c=0,t=0;Object.values(s).forEach(v=>{if(v&&typeof v==='object'){a+=Number(v.attempts||v.total||0);c+=Number(v.correct||0);t+=Number(v.total||v.attempts||0)}});const pct=a?Math.round(c/a*100):0;return{attempts:a,correct:c,total:t,pct};}
  function hero(){const header=$('header .wrap');if(!header||$('.dashboard-hero'))return;header.innerHTML='';const d=document.createElement('div');d.className='dashboard-hero';d.innerHTML=`<div class="hero-copy"><div class="brandline">🎓 SAPIENTIA <small>Conhecimento transforma</small></div><h1>Disciplina hoje,<br><span>conquistas amanhã.</span></h1><p>Questões, conhecimento e evolução para o seu sucesso no concurso da Prefeitura de Itajaí/SC.</p><div class="hero-actions"><button onclick="document.querySelector('#themes')?.scrollIntoView({behavior:'smooth'})">▶ Continuar estudando</button><button class="ghost" onclick="showStats()">📊 Ver estatísticas</button></div></div><div class="hero-art"><div class="book b1">FOCO</div><div class="book b2">ESTUDO</div><div class="book b3">PLANEJAMENTO</div><div class="book b4">DISCIPLINA</div><div class="book b5">RESULTADO</div><div class="sticky">VOCÊ<br>CONSEGUE!<br>☺</div></div>`;header.appendChild(d);}
  function topMetrics(){const home=$('#home');if(!home||$('.metric-strip'))return;const m=calc();const q=typeof DATA!=='undefined'?DATA.length:0;const el=document.createElement('div');el.className='metric-strip';el.innerHTML=`<div class="metric-card"><b>🎯 ${q}</b><span>Questões no banco</span></div><div class="metric-card"><b>📊 ${m.pct}%</b><span>Média de acertos</span></div><div class="metric-card"><b>🔥 ${Number(localStorage.getItem('sapientia_streak')||0)}</b><span>Dias seguidos</span></div><div class="metric-card"><b>🏆 ${Number(localStorage.getItem('sapientia_simulados')||0)}</b><span>Simulados realizados</span></div>`;home.prepend(el);}
  function layoutHome(){const home=$('#home');const themes=$('#themes');if(!home||!themes||$('.home-dashboard'))return;const info=home.querySelector('.card'); if(info) info.remove(); const title=document.createElement('div');title.className='study-title';title.innerHTML='<div><h2>📖 Escolha um tema para estudar</h2><p>Treine por assunto e acompanhe sua evolução.</p></div><input id="themeSearch" placeholder="Buscar tema..." aria-label="Buscar tema">';themes.parentNode.insertBefore(title,themes);
    const shell=document.createElement('div');shell.className='home-dashboard';const left=document.createElement('div');left.className='dashboard-main';const right=document.createElement('aside');right.className='dashboard-side';themes.parentNode.insertBefore(shell,themes);shell.append(left,right);left.append(title,themes);
    const m=calc();right.innerHTML=`<div class="side-card quote">❝ <b>O esforço de hoje<br>é o resultado de amanhã.</b></div><div class="side-card"><h3>📅 Sua sequência de estudos</h3><div class="week"><span>✓<small>Seg</small></span><span>✓<small>Ter</small></span><span>✓<small>Qua</small></span><span>✓<small>Qui</small></span><span>✓<small>Sex</small></span><span>○<small>Sáb</small></span><span>○<small>Dom</small></span></div></div><div class="side-card goal"><h3>🎯 Seu objetivo</h3><p>Concurso Prefeitura de Itajaí/SC</p><div class="goalbar"><i style="width:${m.pct}%"></i></div><b>${m.pct}% de desempenho acumulado</b></div><div class="side-card tip"><h3>💡 Dica do dia</h3><p>“Não estude até cansar. Estude até entender.”</p></div>`;
    const quick=document.createElement('div');quick.className='quick-actions';quick.innerHTML='<button onclick="showStats()">📊 Estatísticas detalhadas</button><button onclick="document.querySelector(\'#themes\')?.scrollIntoView({behavior:\'smooth\'})">🎯 Revisar matérias</button><button onclick="resetStats()">♻️ Reiniciar desempenho</button>';left.appendChild(quick);
    $('#themeSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('#themes .theme').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'':'none')});
  }
  function cards(){ $$('#themes .theme').forEach((card,i)=>{const[icon,color]=themePalette[i%themePalette.length];card.style.setProperty('--theme-color',color);if(!$('.theme-icon',card)){const el=document.createElement('div');el.className='theme-icon';el.textContent=icon;card.prepend(el)} if(!$('.study-now',card)){const b=document.createElement('span');b.className='study-now';b.textContent='Estudar agora →';card.appendChild(b)} if(!$('.theme-progress',card)){const p=document.createElement('div');p.className='theme-progress';p.innerHTML='<span style="width:0%"></span>';card.appendChild(p)}});}
  function run(){hero();topMetrics();layoutHome();cards();const s=$('#count');if(s&&!s.getAttribute('aria-label'))s.setAttribute('aria-label','Quantidade de questões do treino');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
  const obs=new MutationObserver(cards);const t=$('#themes');if(t)obs.observe(t,{childList:true});
})();
